context:
  base_url: "http://localhost:8000"
  current_version: 1.6
  versions:
    - path: policy-archive/policy-version-1-0
      version: 1.0
      date: "2022-03-01"
    - path: policy-archive/policy-version-1-1
      version: 1.1
      date: "2022-06-01"
    - path: policy-archive/policy-version-1-2
      version: 1.2
      date: "2022-09-01"
    - path: policy-archive/policy-version-1-3
      version: 1.3
      date: "2023-01-06"
    - path: policy-archive/policy-version-1-4
      version: 1.4
      date: "2023-03-03"
    - path: policy-archive/policy-version-1-5
      version: 1.5
      date: "2024-01-16"
    - path: /
      version: 1.6
      date: "2025-02-15"
input_dir: content
template_dir: templates
output_dir: output_html
